name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  IMAGE_TAG: ${{ secrets.REGISTRY }}/lion:latest
  CONTAINER_NAME: lion
  CONTAINER_NETWORK: ${{ secrets.CONTAINER_NETWORK }}
  LOCAL_SSH_KEY_PATH: ~/.ssh/id_rsa

jobs:
  build:
    name: Run the latest container image
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          echo "${{ env.SSH_KEY }}" > ${{ env.LOCAL_SSH_KEY_PATH }}
      - name: Run latest container
        run: ssh ${{ env.SSH_USER }}@${{ env.SSH_HOST }} 'podman stop ${{ env.CONTAINER_NAME }} | podman rm ${{ env.CONTAINER_NAME }} | podman run -d --name ${{ env.CONTAINER_NAME }} --network ${{ env.CONTAINER_NETWORK }} -p 8080:8080 ${{ env.IMAGE_TAG }}'
      - name: Cleanup SSH
        run: rm ${{ env.LOCAL_SSH_KEY_PATH }}
