name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

env:
  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  REGISTRY: ${{ secrets.REGISTRY }}
  IMAGE_TAG: ${{ env.REGISTRY }}/lion:latest

jobs:
  build:
    name: Build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container image
        run: podman build -t ${{ env.IMAGE_TAG }} -f containerfile .
      - name: Registry login
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.REGISTRY }}
      - name: Push container image
        run: podman push ${{ env.IMAGE_TAG }}
